version: "3"
services:
  app:
    container_name: productscontainer
    restart: on-failure
    build:
      context: .
      dockerfile: DockerfileNode
    depends_on:
      - postgres
    ports:
      - "80:3000"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres
    build:
      context: .
      dockerfile: DockerfileP
    ports:
      - "5432:5432"